### ISSUE TITLE
Why two registration emails to user?

### ISSUE THREAD

**Issue by ksclarke** [omeka/plugin-GuestUser#23]
User registers and gets an email to confirm they own the email address they've supplied. In that email is a link (with a token) they can click which gets them to confirmAction() in UserController.php

After confirming the token in confirmAction, they see the message "Please check the email we just sent you for the next steps! You're almost there!" and another email is sent to them.

They don't really need to go check their email again though because they can login at this point. I can see sending them another email if there is information they should know now that they are a user of the site, but why tell them there are "next steps" when there aren't?

Am I missing something?

**Comment by patrickmj** [comment]
Looks like it's a (clumsy) difference between open registration, and registration needing approval. When an admin has to approve the signup, the second email points that out. So that message makes sense in that case, but not when registration is open.

I'll rework the messages and emails to be less confusing
